name: gtfs_bindings
description: A utility package to read the contents of a GTFS Schedule dataset.
version: 0.1.0
repository: https://github.com/helomri/gtfs_bindings
issue_tracker: https://github.com/helomri/gtfs_bindings/issues
topics:
  - gtfs
  - parser
  - wrapper

environment:
  sdk: ^3.8.0

dependencies:
  archive: ^4.0.7
  async: ^2.13.0
  csv: ^6.0.0
  geojson_vi: ^2.2.5
  http: ^1.4.0
  intl: ^0.20.2
  logging: ^1.3.0
  mgrs_dart: ^2.0.0
  path: ^1.9.1

dev_dependencies:
  args: ^2.7.0
  lints: ^6.0.0
  markdown: ^7.3.0
  test: ^1.24.0
  yaml: ^3.1.3
